### PR TITLE
fix crash when returning to main menu from pause screen

### LINKED ISSUE #7: Crash when returning to Main Menu from Pause Screen
When in an active game, opening the Pause Screen and then clicking on the Main Menu leads to a crash.

### PR DESCRIPTION
**Pull request by cykler**
fixes #7

### CODE REVIEW

File: js/screens/pause/index.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import React from 'react';
-import { StyleSheet, Text, View, TouchableOpacity, Image } from 'react-native';
```
Comment (maxrimue) [inline js/screens/pause/index.js]: This was unused right? We should get some basic linter magic going to prevent this kinda stuff. Will create a ticket.

Comment (cykler) [reply js/screens/pause/index.js]: Yes, it was obsolete. Introducing ESLint or something is a good idea though!
